### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by moceansystems** [CoderGamester/com.gamelovers.statechart#12]
Any documentation, examples other than the tests?

**Comment by CoderGamester** [comment]
Not yet unfortunately.
We have been using this package internally but I plan to create examples and documentation in the future as soon as I have the time for it.
The tests pretty much cover each state and use case for the package.
I plan also to add more debugging data and add a visual improvement to allow to see and potencially build statecharts via visual nodes.

Let me know if you have any questions I can help you with 👍
